# Generated by Django 2.2.4 on 2020-08-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequests',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('requested_user_name', models.CharField(max_length=100)),
                ('request_type', models.CharField(max_length=100)),
                ('request_discription', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('alternate_ph_number', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
